# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81e96f36de55a623e6d4ae1a85d9352e5dd1456e0b89d70f381398226d0988682a69e97f96b1739aba1ab77a5004942055333dfe1a04355b58e76b8f35c7192e

test:
  secret_key_base: 6fd987f6acc7ee968105d331d67db467f1f6ded390f1960fb7820807d0cea71c5cb6888b554b75cf6e07f104a7891398ad8a3d57cc8e01355b450feeb51da5bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
